#!python
# vim: syntax=python tabstop=4 expandtab
# coding: utf-8

configfile: "../config_files/ALASCCA/config_simulated_AL-P-00045477.json"

rule_dir = "../"

include:
  rule_dir + "snakemake_rules/align/bwa_mem.rule"
include:
  rule_dir + "snakemake_rules/quality_control/cutadapt.rule"
include:
  rule_dir + "snakemake_rules/quality_control/fastqc.rule"
include:
  rule_dir + "snakemake_rules/align/samtools.rule"
include:
  rule_dir + "snakemake_rules/quality_control/picard.rule"
include:
  rule_dir + "snakemake_rules/quality_control/sambamba_depth.rule"
include:
  rule_dir + "snakemake_rules/quality_control/collectqc.rule"
include:
  rule_dir + "snakemake_rules/quality_control/GATK.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/mergetype.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/vardict.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/manta.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/mutect.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/strelka.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/aggregate_vcf.rule"


cutadapt_dir = config["analysis"]["analysis_dir"] + config["analysis"]["sample_id"]  + "/" + config["analysis"]["result"]  + "cutadapt/"
fastqc_dir = config["analysis"]["analysis_dir"] + config["analysis"]["sample_id"]  + "/" + config["analysis"]["result"]  + "fastqc/"
bam_dir = config["analysis"]["analysis_dir"]  + config["analysis"]["sample_id"]  + "/" + config["analysis"]["result"]  + "bam/"
vcf_dir = config["analysis"]["analysis_dir"]  + config["analysis"]["sample_id"]  + "/" + config["analysis"]["result"]  + "vcf/"
result_dir = config["analysis"]["analysis_dir"]  + config["analysis"]["sample_id"]  + "/" + config["analysis"]["result"]

rule all:
  input:
    #expand(bam_dir + "{mysample}.bam", mysample=config["samples"]),
    #expand(bam_dir + "{mysample}.sorted.bam", mysample=config["samples"]),
    #expand(bam_dir + "{mysample}.sorted.rmdup.bam", mysample=config["samples"]),
    #expand(bam_dir + "{mysample}.sorted.rmdup.hsmetric", mysample=config["samples"]),
    #expand(bam_dir + "{mysample}.sorted.rmdup.cov.bed", mysample=config["samples"]),
    #expand(bam_dir + "{mysample}.sorted.rmdup.intervals", mysample=config["samples"]),
    #expand(bam_dir + "{mysample}.sorted.rmdup.ralgn.bam", mysample=config["samples"]),
    #expand(bam_dir + "{mysample}.sorted.rmdup.ralgn.bsrcl.bam", mysample=config["samples"]),
    result_dir + "qc/" + "qc_report.pdf",
    vcf_dir + "combined_vcf.vcf", 
    #expand(vcf_dir + manta_dir + "{vcf_file}", vcf_file=config["vcf"]["manta"]),
    #expand(vcf_dir + strelka_dir + "{vcf_file}", vcf_file=config["vcf"]["strelka"]),
    #vcf_dir + vardict_dir + config["vcf"]["vardict"],
