---

owner: cust000

family: 'lovingtiger'
family_name: 'lovingtiger'
samples:
  - analysis_type: panel
    sample_id: tumor
    tumor_type: unknown 
    capture_kit: capture_kit_name
    sample_name: tumor
    phenotype: affected
    sex: unknown 
    expected_coverage: unknown 
    tmb: unknown 
    msi: unknown
    tumor_purity: unknown 
    bam_path: path_tumor_merged.bam 

  - analysis_type: panel
    sample_id: normal
    capture_kit: capture_kit_name 
    sample_name: normal
    phenotype: unaffected
    sex: unknown 
    expected_coverage: unknown 
    bam_path: path_tumor_merged.bam 

vcf_cancer: path_to_final_vcf 
vcf_cancer_sv: path_to_final_vcf 

multiqc: path_multiqc_report 

default_gene_panels: [panel1]
gene_panels: [panel1]

# meta data
rank_model_version: '1.1'
rank_score_threshold: -100
analysis_date: 'N/A' 
human_genome_build: 37
track: cancer
