language: python

python:
  - '3.6'

install:
  - pip install pytest
  - pip install pytest-cov
  - pip install --editable .

script:
  - py.test -v --cov tests/*

after_success: coveralls
  
notification:
  - email: false
