sudo: true

language: python

python:
  - '3.6'

before_install:
  - sudo apt-get install python3-dev graphviz libgraphviz-dev pkg-config

install:
  - pip install cython
  - pip install pygraphviz pygments 'cyvcf2<0.10.0'
  - pip install -r requirements-dev.txt -r requirements.txt -e .

script:
  - py.test --cov=BALSAMIC -rsxv tests/* 

after_success: coveralls

env:
  - SENTIEON_LICENSE="/path/to/sentieon_license" SENTIEON_INSTALL_DIR="/path/to/sentieon_install_dir"

notification:
  - email: false
