sudo: true

language: python

python:
  - '3.6'

install:
  - pip install -r requirements-dev.txt -r requirements.txt -e .

 cript:
  - py.test --cov=BALSAMIC -r tests/commands/run/* tests/*

after_success: coveralls

notification:
  - email: false
