language: python

python:
  - '3.6'

install:
  - pip install pytest pytest-cov coveralls
  - pip install --editable .

script:
  - py.test --cov tests/*

after_success: coveralls
  
notification:
  - email: false
