sudo: true

language: python

python:
  - '3.6'

before_install:
  - sudo apt-get install graphviz

install:
  - pip install -r requirements-dev.txt -r requirements.txt -e .

script:
  - py.test --cov=BALSAMIC -rsxv tests/* 
  - mkdir -p reference/GRCh37 && cp tests/test_data/references/reference.json reference/GRCh37/reference.json
  - mkdir run_tests
  
  - ./run_validate.sh -a T -m all -t panel
  - ./run_validate.sh -a TN -m all -t panel
  - ./run_validate.sh -a T -m all -t WGS
  - ./run_validate.sh -a TN -m all -t WGS

after_success: coveralls

env:
  - SENTIEON_LICENSE="/path/to/sentieon_license" SENTIEON_INSTALL_DIR="/path/to/sentieon_install_dir"
  
notification:
  - email: false
