jobs: 999
default-resources:
    runtime: 120
    mem_mb: 4000
    threads: 2
    slurm_partition: "core"
    slurm_account: "development"
    slurm_extra: "'--qos high'"
restart-times: 3
max-status-checks-per-second: 1
local-cores: 1
executor: slurm
slurm:
  time: "{resources.runtime}"
  mem: "{resources.mem_mb}"
  cpus-per-task: "{resources.threads}"