#!python
# vim: syntax=python tabstop=4 expandtab
# coding: utf-8

import os
from BALSAMIC.utils.rule import get_vcf
from BALSAMIC.utils.rule import get_result_dir

shell.prefix("set -eo pipefail; ")

rule_dir = config["rule_directory"]
fastq_dir = config["analysis"]["fastq_path"]
bam_dir = get_result_dir(config) + "/bam/"
cnv_dir = get_result_dir(config) + "/cnv/"
cutadapt_dir = get_result_dir(config) + "/cutadapt/"
fastqc_dir = get_result_dir(config) + "/fastqc/"
result_dir = get_result_dir(config) + "/"
vcf_dir = get_result_dir(config) + "/vcf/"
vep_dir = get_result_dir(config) + "/vep/"

SENTIEON_LICENSE = "10.10.10.1:8990"  
SENTIEON_INSTALL_DIR="/home/proj/development/cancer/sentieon/sentieon-genomics-201808.03"
SENTIEON_DNASCOPE = "$SENTIEON_DNASCOPE_ML"
SENTIEON_TNSCOPE = "$SENTIEON_TNSCOPE"

include:
  os.path.join(rule_dir , "snakemake_rules/quality_control/fastp.rule") 
include:
  os.path.join(rule_dir , "snakemake_rules/sentieon/sentieon_alignment.rule") 
include:
  os.path.join(rule_dir , "snakemake_rules/sentieon/sentieon_tn_varcall.rule") 

rule all:
  input:
    expand(bam_dir + "{sample}.bam", sample=config["samples"]),
    expand(bam_dir + "{sample}.dedup.bam", sample=config["samples"]),
    expand(bam_dir + "{sample}.dedup.realign.bam", sample=config["samples"]),
    expand(bam_dir + "{sample}.dedup.realign.recal_data.table", sample=config["samples"]),
    expand(bam_dir + "{sample}.dedup.realign.recal.csv", sample=config["samples"]),
    expand(bam_dir + "{sample}.dedup.realign.recal.pdf", sample=config["samples"]),
    bam_dir + config["analysis"]["case_id"] + ".corealign.bam",
    expand(vcf_dir +  "SNV.somatic." + config["analysis"]["case_id"] + ".{algo}.vcf.gz", algo = ["tnsnv", "tnhaplotyper"]),
    expand(vcf_dir + config["analysis"]["case_id"] + ".{caller}.vcf.gz", caller = ["tnscope","tnscope.filtered"]),
    expand(vcf_dir + "SNV.germline.{sample}.dnascope.vcf.gz", sample=config["samples"])
  output:
    os.path.join(get_result_dir(config), "analysis_finish")
  shell:
    "date +'%Y-%M-%d T%T %:z' > {output}"
