#!python
# vim: syntax=python tabstop=4 expandtab
# coding: utf-8

import os
from BALSAMIC.utils.rule import get_vcf
from BALSAMIC.utils.rule import get_result_dir

shell.prefix("set -eo pipefail; ")

rule_dir = config["rule_directory"]
fastq_dir = get_result_dir(config) + "/fastq/"
bam_dir = get_result_dir(config) + "/bam/"
cnv_dir = get_result_dir(config) + "/cnv/"
cutadapt_dir = get_result_dir(config) + "/cutadapt/"
fastqc_dir = get_result_dir(config) + "/fastqc/"
result_dir = get_result_dir(config) + "/"
vcf_dir = get_result_dir(config) + "/vcf/"
vep_dir = get_result_dir(config) + "/vep/"

include:
  rule_dir + "snakemake_rules/align/bwa_mem.rule"
include:
  rule_dir + "snakemake_rules/quality_control/fastp.rule"
include:
  rule_dir + "snakemake_rules/quality_control/fastqc.rule"
include:
  rule_dir + "snakemake_rules/align/samtools.rule"
include:
  rule_dir + "snakemake_rules/quality_control/picard.rule"
include:
  rule_dir + "snakemake_rules/quality_control/sambamba_depth.rule"
include:
  rule_dir + "snakemake_rules/quality_control/multiqc.rule"
include:
  rule_dir + "snakemake_rules/quality_control/GATK.rule"
include:
  rule_dir + "snakemake_rules/quality_control/contest.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/mergetype.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/vardict.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/split_bed.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/cnvkit_paired.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/manta.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/mutect.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/strelka.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/strelka_germline.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/manta_germline.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/freebayes.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/haplotypecaller.rule"
include:
  rule_dir + "snakemake_rules/annotation/vep.rule"

ar_type = ["SNV", "SV"]
var_class = ["somatic", "germline"]

rule all:
  input:
    os.path.join(*([result_dir + "qc/" + "multiqc_report.html"])),
    cnv_dir + "cnvkit_paired.done",
    expand(vep_dir + "{vcf}.vcf.gz", vcf=get_vcf(config, ["mutect", "vardict", "strelka", "manta"], [config["analysis"]["sample_id"]])),
    expand(vep_dir + "{vcf}.tbl", vcf=get_vcf(config, ["mutect", "vardict", "strelka"], [config["analysis"]["sample_id"]])),
    expand(vep_dir + "{vcf}.vcf.gz", vcf=get_vcf(config, ["freebayes", "haplotypecaller", "strelka_germline", "manta_germline"], config["samples"])),
  output:
    os.path.join(get_result_dir(config), "analysis_finish")
  shell:
    "date +'%Y-%M-%d T%T %:z' > {output}"
