#!python
# vim: syntax=python tabstop=4 expandtab
# coding: utf-8

import os
from BALSAMIC.tools import get_result_dir, get_vcf

shell.prefix("set -eo pipefail; ")

rule_dir = config["rule_directory"]

include:
  rule_dir + "snakemake_rules/align/bwa_mem_umi.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/split_bed.rule"
include:
  rule_dir + "snakemake_rules/quality_control/picard.rule"
include:
  rule_dir + "snakemake_rules/umi/fgbio.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/mergetype_paired_umi.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/vardict.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/strelka.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/manta.rule"

bam_dir = get_result_dir(config) + "/bam/"
vcf_dir = get_result_dir(config) + "/vcf/"
vep_dir = get_result_dir(config) + "/vep/"

var_type = ["SNV", "SV"]
var_class = ["somatic", "germline"]

rule all:
  input:
    expand(vcf_dir + "{vcf}.vcf.gz", vcf=get_vcf(config, ["vardict", "strelka"], [config["analysis"]["sample_id"]])),
    expand(bam_dir + "{sample}.unalg.umi.mrkadp.bwa.map.umi.cnsunalg.bwa.map.fltr.clip.bam", sample=config["samples"]),
    expand(bam_dir + "{sample}.unalg.umi.mrkadp.bwa.map.umi.metrics", sample=config["samples"])
  params:
    analysis_finish_file = os.path.join(get_result_dir(config), "analysis_finish") 
  shell:
    "date +'%Y-%M-%d T%T %:z' > {params.analysis_finish_file}"
