#!python
# vim: syntax=python tabstop=4 expandtab
# coding: utf-8

import os
from BALSAMIC.tools import get_vcf
from BALSAMIC.tools import get_result_dir
from BALSAMIC.tools import get_chrom

shell.prefix("set -eo pipefail; ")

rule_dir = config["rule_directory"]

include:
  rule_dir + "snakemake_rules/align/bwa_mem.rule"
include:
  rule_dir + "snakemake_rules/quality_control/cutadapt.rule"
include:
  rule_dir + "snakemake_rules/quality_control/fastqc.rule"
include:
  rule_dir + "snakemake_rules/align/samtools.rule"
include:
  rule_dir + "snakemake_rules/quality_control/picard.rule"
include:
  rule_dir + "snakemake_rules/quality_control/sambamba_depth.rule"
include:
  rule_dir + "snakemake_rules/quality_control/collectqc_single.rule"
include:
  rule_dir + "snakemake_rules/quality_control/GATK.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/split_bed.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/mergetype_tumor.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/vardict_single.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/cnvkit_single.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/manta_single.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/mutect_single.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/strelka_germline.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/manta_germline.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/freebayes.rule"
include:
  rule_dir + "snakemake_rules/variant_calling/haplotypecaller.rule"
include:
  rule_dir + "snakemake_rules/annotation/vep.rule"

bam_dir = get_result_dir(config) + "/bam/"
cnv_dir = get_result_dir(config) + "/cnv/"
vcf_dir = get_result_dir(config) + "/vcf/"
vep_dir = get_result_dir(config) + "/vep/"

var_type = ["SNV", "SV"]
var_class = ["somatic", "germline"]

rule all:
  input:
    os.path.join(*([result_dir + "qc/" + "qc_report.pdf"])),
    expand(vep_dir + "{vcf}.vcf.gz", vcf=get_vcf(config, ["mutect", "vardict", "manta"], [config["analysis"]["sample_id"]])),
    expand(vep_dir + "{vcf}.tbl", vcf=get_vcf(config, ["mutect", "vardict"], [config["analysis"]["sample_id"]])),
    expand(vep_dir + "{vcf}.vcf.gz", vcf=get_vcf(config, ["freebayes", "haplotypecaller", "strelka_germline", "manta_germline"], config["samples"])),
    expand(cnv_dir + "{sample}.cnvkit_single.done", sample = config["samples"])
    #expand(vep_dir + "vep_" + "{vcf}", vcf=list(map(lambda vcf: str.replace(vcf,".gz",""), get_vcf_files(config, "SNV") + get_vcf_files(config, "SV")))),
  params:
    analysis_finish_file = os.path.join(get_result_dir(config), "analysis_finish") 
  shell:
    "date +'%Y-%M-%d T%T %:z' > {params.analysis_finish_file}"
