#!python
# vim: syntax=python tabstop=4 expandtab
# coding: utf-8


import os

from yapf.yapflib.yapf_api import FormatFile
from snakemake.logging import logger
from BALSAMIC.utils.cli import write_json
from BALSAMIC.utils.rule import get_rule_output 
from BALSAMIC.utils.rule import get_result_dir
from BALSAMIC import __version__ as bv


shell.prefix("set -eo pipefail; ")

result_dir = get_result_dir(config) + "/"
fastq_dir = result_dir + "fastq/"
bam_dir = result_dir +" bam/"
cnv_dir = result_dir + "cnv/"
cutadapt_dir = result_dir + "cutadapt/"
fastqc_dir = result_dir + "fastqc/"
vcf_dir = result_dir + "vcf/"
vep_dir = result_dir + "vep/"
qc_dir = result_dir + "qc/"
benchmark_dir = config["analysis"]["benchmark"]
singularity_image = config['singularity']['image']


