name: Assessment
description: An assessment for BALSAMIC
title: "[Assessment] <title>"
labels: ["Assessment"]
projects: ["Clinical-Genomics/46"]
body:
- type: textarea
  attributes:
    label: Description
    description: Describe what you want to assess/evaluate
  validations:
    required: false
- type: textarea
  attributes:
    label: Suggested approach
    description: A few sentences about how the work will be done
  validations:
    required: false
- type: textarea
  attributes:
    label: Criteria
    description: List the criteria which will be evaluated
  validations:
    required: false
- type: textarea
  attributes:
    label: Origin
    description: Link to tickets, issues, discussion etc from where this originated
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the work at hand.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
    
