name: Bug report
description: A bug report for BALSAMIC
title: "[Bug] <title>"
labels: ["Bug"]
projects: ["Clinical-Genomics/46"]
body:
- type: textarea
  attributes:
    label: Description
    description: A clear and concise description of what the bug is
  validations:
    required: false
- type: textarea
  attributes:
    label: How to reproduce
    description: Steps to reproduce the bug
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected behaviour
    description: A clear and concise description of what you expected to happen
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? Screenshots? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: input
  attributes:
    label: Pipeline version
    description: Pipeline version used when encountering the bug
  validations:
    required: false
