name: User Story
description: A user story for BALSAMIC
title: "[User Story] <title>"
labels: ["User-Story"]
projects: ["Clinical-Genomics/46"]
body:
- type: textarea
  attributes:
    label: Need
    description: Describe the need for the perspective of the user
    placeholder: As a ROLE, I want FUNCTIONALITY beacause of REASON
  validations:
    required: false
- type: textarea
  attributes:
    label: Suggested approach
    description: A few sentences about the intended solution
  validations:
    required: false
- type: textarea
  attributes:
    label: Considered alternatives
    description: Were there alternative approaches which have been rejected?
  validations:
    required: false
- type: input
  attributes:
    label: Deviation
    description: If there is a deviation, add a link to it here
    placeholder: Link to deviation
  validations:
    required: false
- type: checkboxes
  attributes:
    label: System requirements assessed
    description: Have you reviewed if the existing system requirements are affected by this change?
    options:
      - label: Yes, I have reviewed the system requirements
- type: textarea
  attributes:
    label: Requirements affected by this story
    description: Link any requirements affected, or motivate why no requirements are affected.
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Risk assessment
    description: Is a risk assessment needed or not for this user story?
    options:
      - label: Needed
      - label: Not needed
- type: textarea
  attributes:
    label: Risk assessment
    description: If a risk assessment is needed, link to it here. If no, motivate why not.
    placeholder: 
  validations:
    required: false
- type: textarea
  attributes:
    label: Can be closed when
    description: Link the issues/PRs needed to be closed for this to be implemented
  validations:
    required: false
- type: textarea
  attributes:
    label: Blockers
    description: Anything preventing this from happening?
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
