align_qc:
  - bedtools
  - bwa
  - fastqc
  - samtools
  - picard
  - multiqc
  - fastp
  - csvkit
annotate:
  - ensembl-vep
coverage_qc:
  - sambamba
  - mosdepth
varcall_py36:
  - bcftools
  - tabix
  - gatk
  - vardict
  - cnvkit
  - libiconv
varcall_py27:
  - strelka
  - manta
vcf_merge:
  - vcfmerge
