align_qc:
  - bedtools
  - bwa
  - fastqc
  - samtools
  - picard
  - multiqc
  - fastp
annotate:
  - ensembl-vep
  - vcfanno
coverage_qc:
  - sambamba
  - mosdepth
varcall_py36:
  - bcftools
  - tabix
  - gatk
  - vardict
  - libiconv
  - svdb
varcall_py27:
  - manta
varcall_cnvkit:
  - cnvkit
  - purecn
vcf_merge:
  - vcfmerge
delly:
  - delly
ascatNgs:
  - ascat
vcf2cytosure:
  - vcf2cytosure
