align:
  - bedtools
  - bwa
  - fastqc
  - samtools
  - tabix
  - gatk
  - picard
  - multiqc
  - fastp
  - csvkit
  - libiconv
annotate:
  - python
  - pip
  - ensembl-vep
coverage:
  - sambamba
  - mosdepth
varcall_py36:
  - bcftools
  - tabix
  - gatk
  - vardict
  - cnvkit
  - libiconv
varcall_py27:
  - python
  - strelka
  - manta
  - bcftools
  - tabix
  - samtools
vcf_merge:
  - vcfmerge
