[[annotation]]
file="gnomad.genomes.r2.1.1.sites.vcf.bgz"
fields = ["AF", "AF_popmax"]
ops=["self", "self"]
names=["GNOMADAF", "GNOMADAF_popmax"]

[[annotation]]
file="clinvar.vcf.gz"
fields=["CLNACC", "CLNREVSTAT", "CLNSIG", "ORIGIN", "CLNVC", "CLNVCSO"]
ops=["self", "self","self","self","self","self"]
names=["CLNACC", "CLNREVSTAT", "CLNSIG", "ORIGIN", "CLNVC", "CLNVCSO"]
