FROM hassanf/miniconda3:version-4.6.14

LABEL maintainer="Hassan Foroughi hassan dot foroughi at scilifelab dot se" 
LABEL description="Bioinformatic analysis pipeline for somatic mutations in cancer"
LABEL version="6.1.0"

ARG GIT_BRANCH=v6.1.0

# create necessary directories
# install balsamic and it's environments
# symlink libreadline for picard to function properly 
RUN mkdir -p /git_repos; \
    export PATH=/usr/local/miniconda/bin:$PATH; \
    export LC_ALL=en_US.utf-8; \
    export LANG=en_US.utf-8; \
    conda clean -iy; \
    cd /git_repos && git clone https://github.com/Clinical-Genomics/BALSAMIC && cd BALSAMIC && git checkout ${GIT_BRANCH} && \
    conda env create --file BALSAMIC/conda/align.yaml -n align_qc && \
    source activate align_qc && \
    picard_jar=picard-2.23.2-201-g922891d-SNAPSHOT-all.jar && \
    picard_PATH=BALSAMIC/assets/${picard_jar} && \
    picard_destination=/usr/local/miniconda/envs/align_qc/share/ && \
    cp $picard_PATH ${picard_destination} && \
    ln -s ${picard_destination}/${picard_jar} ${picard_destination}/picard.jar; \
    ln -s /usr/local/miniconda/envs/align_qc/lib/libreadline.so.7.0 /usr/local/miniconda/envs/align_qc/lib/libreadline.so.6 && \
    ln -s /usr/local/miniconda/envs/align_qc/lib/libreadline.so.7.0 /usr/local/miniconda/envs/align_qc/lib/libreadline.so.6.0 && \
    source deactivate && \
    conda env create --file BALSAMIC/conda/annotate.yaml -n annotate && \
    conda env create --file BALSAMIC/conda/coverage.yaml -n coverage_qc && \
    conda env create --file BALSAMIC/conda/varcall_py27.yaml -n varcall_py27 && \
    conda env create --file BALSAMIC/conda/varcall_py36.yaml -n varcall_py36 && \
    source activate varcall_py36 && \
    ln -s /usr/local/miniconda/envs/varcall_py36/lib/libreadline.so.7.0 /usr/local/miniconda/envs/varcall_py36/lib/libreadline.so.6 && \
    ln -s /usr/local/miniconda/envs/varcall_py36/lib/libreadline.so.7.0 /usr/local/miniconda/envs/varcall_py36/lib/libreadline.so.6.0 && \
    source deactivate && \
    conda env create --file BALSAMIC/conda/varcall_cnvkit.yaml -n varcall_cnvkit && \
    conda clean --index-cache --lock --tarballs -y

# The following fixes the error for Click
# RuntimeError: Click will abort further execution because Python 3 was
# configured to use ASCII as encoding for the environment. Consult
# https://click.palletsprojects.com/en/7.x/python3/ for mitigation steps.
ENV LC_ALL=en_US.utf-8
ENV LANG=en_US.utf-8
ENV PATH="/usr/local/miniconda/bin:${PATH}"

