name: Black linter and code formatter
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          version: "22.3.0"
