name: Black linter and code formatter
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          version: "24.4.2"
