name: build test container submodule

# Tigger building and testing container only on pull requests
on: ["push"]

jobs:
  main:
    name: Docker image build test 
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        id: git_checkout
        uses: actions/checkout@v2
        with:
            submodules: recursive
      - name: Get branch name
        id: get_branch_name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
      - name: Login to DockerHub
        id: docker_login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build only 
        id: docker_build_only
        uses: docker/build-push-action@v2
        with:
          context: ascatNgs
          push: false 
          tags: clinicalgenomics/balsamic:${{ steps.get_branch_name.outputs.branch }}-ascatngs 
