name: build an push docker containers

# Tigger building and testing container only on pull requests
on: ["push"]

jobs:
  main:
    name: Docker image build test 
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true
      matrix: 
        container-name: [align_qc, annotate, coverage_qc, varcall_cnvkit, varcall_py27, varcall_py36]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false 
          tags: clinicalgenomics/balsamic:${GITHUB_REF##*/}-${{ matrix.container-name }} 
          build-args:
            CONTAINER_NAME=${{ matrix.container-name }}
