name: latest release container
# Trigger building and testing container only on pull requests
on:
  push:
    tags:
      - "**"
jobs:
  main:
    name: Docker image build push
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        container-name: [align_qc, annotate, coverage_qc, varcall_cnvkit, varcall_py27, varcall_py3, balsamic, delly, vcf2cytosure]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Get branch name
        id: get_branch_name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
      - name: Login to DockerHub
        id: docker_login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build_push
        uses: docker/build-push-action@v3
        with:
          file: BALSAMIC/containers/${{ matrix.container-name }}/Dockerfile
          push: true
          tags: clinicalgenomics/balsamic:release_${{ steps.get_branch_name.outputs.branch }}-${{ matrix.container-name }}
          build-args: CONTAINER_NAME=${{ matrix.container-name }}
