name: Docker develop containers
on:
  push:
    branches:
      - "develop"
  pull_request:
    branches-ignore:
      - "master"
    paths:
      - "BALSAMIC/containers/**"
jobs:
  main:
    name: Build and publish
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        container-name: [align_qc, annotate, ascatNgs, cadd, cnvkit, cnvpytor, coverage_qc, delly, gatk, htslib, purecn, somalier, varcall_py3, varcall_py27, vcf2cytosure]
    steps:
      - name: Git checkout
        id: git_checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        id: docker_login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build_push
        uses: docker/build-push-action@v3
        with:
          file: BALSAMIC/containers/${{ matrix.container-name }}/Dockerfile
          push: true
          tags: clinicalgenomics/balsamic:develop-${{ matrix.container-name }}
          build-args: CONTAINER_NAME=${{ matrix.container-name }}
          provenance: false
      - name: Prune containers
        id: docker_prune_containers
        shell: bash
        run: |
          docker system prune -a -f
      - name: Test container
        id: docker_test_container
        shell: bash
        run: |
          docker run \
          -v $(readlink -f container_tests):/container_tests \
          clinicalgenomics/balsamic:develop-${{ matrix.container-name }} \
          bash /container_tests/${{ matrix.container-name }}/${{ matrix.container-name }}.sh
