name: Docker release containers
on:
  pull_request:
    branches:
      - "master"
jobs:
  main:
    name: Build and publish
    if:  startsWith(github.head_ref, 'release_v')
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        container-name: [align_qc, annotate, ascatNgs, cadd, cnvkit, cnvpytor, coverage_qc, delly, htslib, somalier, varcall_cnvkit, varcall_py3, varcall_py27, vcf2cytosure]
    steps:
      - name: Git checkout
        id: git_checkout
        uses: actions/checkout@v3
      - name: Get branch name
        id: get_branch_name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF##*/}}" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        id: docker_login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build_push
        uses: docker/build-push-action@v3
        with:
          file: BALSAMIC/containers/${{ matrix.container-name }}/Dockerfile
          push: true
          tags: clinicalgenomics/balsamic:${{ steps.get_branch_name.outputs.branch }}-${{ matrix.container-name }}
          build-args: CONTAINER_NAME=${{ matrix.container-name }}
          provenance: false
      - name: Test container
        id: docker_test_container
        shell: bash
        run: |
          docker run \
          -v $(readlink -f container_tests):/container_tests \
          clinicalgenomics/balsamic:${{ steps.get_branch_name.outputs.branch }}-${{ matrix.container-name }} \
          bash /container_tests/${{ matrix.container-name }}/${{ matrix.container-name }}.sh
