name: "Check changelog"
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]
jobs:
  # Enforces the update of a changelog file on every pull request
  changelog:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dangoslen/changelog-enforcer@v3
        with:
          changeLogPath: 'CHANGELOG.rst'
          skipLabels: 'Skip-Changelog'
