name: "Pull Request Docs Check"
on:
  pull_request:
    paths:
      - "docs/**"
    branches:
      - master
jobs:
  docs:
    runs-on: ubuntu-22.04
    steps:
      # Checkout BALSAMIC
      - name: Git checkout
        id: git_checkout
        uses: actions/checkout@v3
      - name: Sphinx build action
        id: sphinx_docs
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
          pre-build-command: "pip install -r requirements-dev.txt && python setup.py install"
          build-command: "sphinx-build -T -E -b html -d _build/doctrees-readthedocs -D language=en . _build/html"
