name: Check URLs
on:
  push:
    branches:
      - master
      - develop
jobs:
  main:
    name: Find broken cache and documentation links
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        id: git_checkout
        uses: actions/checkout@v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --user-agent 'curl/8.4.0' './BALSAMIC/constants/cache.py' './docs/*.rst'
          fail: true
