name: Check URLs
on:
  push:
    branches:
      - master
      - develop
      - fix_broken_cache_doc_links
jobs:
  main:
    name: Find broken cache and documentation links
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        id: git_checkout
        uses: actions/checkout@v3
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2.0.2
        with:
          args: --max-redirects 10 --verbose './BALSAMIC/constants/cache.py' './docs/*.rst'
          fail: true
